# Generated by Django 2.2 on 2020-07-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200724_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='title',
            field=models.CharField(default='My title', max_length=200, verbose_name='Название'),
        ),
    ]
